# Generated by Django 5.1.15 on 2026-03-03 12:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_id', models.CharField(help_text="Wazuh agent ID (e.g. '001').", max_length=20)),
                ('scan_date', models.DateTimeField(help_text='Timestamp when the scan was performed / ingested.')),
                ('overall_score', models.FloatField(default=0.0, help_text='Weighted compliance score (0-100%).', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Compliance Scans',
                'ordering': ['-scan_date'],
            },
        ),
        migrations.CreateModel(
            name='Framework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Framework name, e.g. 'ISO 27001'", max_length=120, unique=True)),
                ('version', models.CharField(help_text="Version identifier, e.g. '2022'", max_length=30)),
                ('description', models.TextField(blank=True, default='', help_text='Optional long description of the framework.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Frameworks',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_code', models.CharField(help_text="Control identifier, e.g. 'A.9.2.4'", max_length=30)),
                ('title', models.CharField(help_text='Short title of the control.', max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text='Full description of what the control requires.')),
                ('weight', models.FloatField(default=1.0, help_text='Relative weight used in compliance score calculation.', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controls', to='compliance.framework')),
            ],
            options={
                'verbose_name_plural': 'Controls',
                'ordering': ['framework', 'control_code'],
                'unique_together': {('framework', 'control_code')},
            },
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text='Full policy text or summary.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('controls', models.ManyToManyField(blank=True, help_text='Controls this policy satisfies.', related_name='policies', to='compliance.control')),
            ],
            options={
                'verbose_name_plural': 'Policies',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('severity', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Low', max_length=10)),
                ('risk_score', models.PositiveSmallIntegerField(help_text='Risk score from 1 (minimal) to 10 (catastrophic).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('remediation_steps', models.TextField(blank=True, default='', help_text='Actionable steps to mitigate or eliminate this risk.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='compliance.control')),
            ],
            options={
                'verbose_name_plural': 'Risks',
                'ordering': ['-risk_score'],
            },
        ),
        migrations.CreateModel(
            name='WazuhMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wazuh_rule_id', models.CharField(help_text="Wazuh SCA check / rule ID (e.g. '28504').", max_length=50, unique=True)),
                ('rule_description', models.TextField(blank=True, default='', help_text='Human-readable description of the Wazuh rule.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wazuh_mappings', to='compliance.control')),
            ],
            options={
                'verbose_name': 'Wazuh → Control Mapping',
                'verbose_name_plural': 'Wazuh → Control Mappings',
            },
        ),
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_passed', models.BooleanField(default=False, help_text='True if the agent passed this check.')),
                ('raw_log_data', models.JSONField(blank=True, default=dict, help_text='Raw JSON payload returned by the Wazuh SCA API.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='compliance.compliancescan')),
                ('mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_results', to='compliance.wazuhmapping')),
            ],
            options={
                'verbose_name_plural': 'Scan Results',
                'ordering': ['-scan__scan_date'],
            },
        ),
    ]
