# Generated by Django 5.1.15 on 2026-03-27 16:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0002_auditlog_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passing_score_threshold', models.IntegerField(default=80, help_text='Compliance score below this value triggers Critical status.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('scan_frequency', models.CharField(choices=[('daily', 'Daily (Recommended for High Risk)'), ('weekly', 'Weekly (Standard)'), ('monthly', 'Monthly')], default='weekly', max_length=10)),
                ('audit_log_retention', models.CharField(choices=[('6months', '6 Months'), ('1year', '1 Year (ISO Requirement)'), ('3years', '3 Years')], default='1year', max_length=10)),
                ('critical_email_alerts', models.BooleanField(default=True)),
                ('weekly_report', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
