# Generated by Django 5.1.15 on 2026-03-27 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0003_systemsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('draft', 'Draft'), ('disabled', 'Disabled')], default='active', max_length=10),
        ),
    ]
