# Generated by Django 5.1.15 on 2026-04-08 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0004_policy_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='totp_secret',
            field=models.CharField(blank=True, default='LNQQV4GJKFA27GFQQWVUELXUX7MECTFI', help_text='Base32 TOTP secret for 2FA authenticator app.', max_length=64),
        ),
    ]
