# Generated by Django 5.1.15 on 2026-04-08 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0005_userprofile_totp_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='password_changed_at',
            field=models.DateTimeField(blank=True, help_text="Timestamp of the user's last self-initiated password change.", null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='totp_secret',
            field=models.CharField(blank=True, default='', help_text='Base32 TOTP secret for 2FA authenticator app.', max_length=64),
        ),
    ]
