# Generated by Django 5.1.15 on 2026-04-10 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0006_userprofile_password_changed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='account_expiry_date',
            field=models.DateTimeField(blank=True, help_text='If set, the account will be automatically deactivated after this date.', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='designation',
            field=models.CharField(blank=True, default='', help_text='Job title or department', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='display_name',
            field=models.CharField(blank=True, default='', help_text="User's real name", max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, default='', help_text='Contact number for emergency / manage admins', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='User avatar', null=True, upload_to='profile_pics/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='timezone',
            field=models.CharField(default='UTC', help_text='User timezone preference', max_length=50),
        ),
    ]
