# Generated by Django 5.1.15 on 2026-04-20 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0008_smtp_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_pic_binary',
            field=models.BinaryField(blank=True, help_text='Binary image data compressed and stored directly in DB', null=True),
        ),
    ]
