# Generated by Django 5.1.15 on 2026-05-03 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0009_remove_userprofile_profile_picture_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Department name, e.g. 'HR', 'IT'", max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='', help_text='Optional description.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Departments',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='status',
            field=models.CharField(choices=[('Success', 'Success'), ('Failed', 'Failed'), ('Alert', 'Alert'), ('System', 'System')], default='System', max_length=10),
        ),
        migrations.CreateModel(
            name='AgentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_id', models.CharField(help_text="Wazuh agent ID (e.g. '001').", max_length=20, unique=True)),
                ('wazuh_name', models.CharField(blank=True, default='', help_text='Name as registered in the Wazuh server.', max_length=255)),
                ('custom_alias', models.CharField(blank=True, default='', help_text='Custom human-readable name assigned by the admin.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, help_text='Department this PC/agent belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='compliance.department')),
            ],
            options={
                'verbose_name': 'Agent Profile',
                'verbose_name_plural': 'Agent Profiles',
                'ordering': ['agent_id'],
            },
        ),
        migrations.AddField(
            model_name='policy',
            name='departments',
            field=models.ManyToManyField(blank=True, help_text='Departments this policy belongs to.', related_name='policies', to='compliance.department'),
        ),
    ]
