# Generated by Django 5.1.15 on 2026-05-03 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0010_department_alter_auditlog_status_agentprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='total_reports_generated',
            field=models.PositiveIntegerField(default=0, help_text='Global count of all compliance reports generated across all users.'),
        ),
    ]
