with open('chapter1.tex', 'r', encoding='utf-8') as f:
    text = f.read()

replacements = {
    "Historical security auditing methodologies rely on manual evidence collection and point-in-time assessments. Organizations traditionally compile spreadsheets and static configuration snapshots to satisfy periodic regulatory requirements. This approach creates significant temporal blind spots, as the security posture remains unverified between audit cycles. Configuration drift often occurs within hours of a successful audit, leaving the infrastructure vulnerable to exploitation while maintaining a formal status of compliance.":
    "Historical security auditing methodologies rely on manual evidence collection and point-in-time assessments. Organizations compile spreadsheets and static configuration snapshots to satisfy regulatory requirements. This approach creates temporal blind spots because the security posture remains unverified between audit cycles. Configuration drift occurs frequently after successful audits, leaving infrastructure vulnerable to exploitation despite maintaining formal compliance status.",

    "The cybersecurity industry addresses these vulnerabilities by transitioning toward Continuous Controls Monitoring (CCM). This paradigm shift replaces manual sampling with automated, real-time validation of security controls. CCM platforms integrate directly with the technical environment to evaluate configurations, access logs, and system integrity continuously. This automation ensures that compliance reflects the actual, current state of the environment rather than a historical record. Modern regulatory mandates codify the requirement for continuous visibility. NIST Special Publication 800-53 Revision 5 emphasizes the transition from static control assessments to ongoing monitoring to validate system integrity \\cite{nist80053_2020}. Similarly, the ISO/IEC 27001:2022 standard requires organizations to establish an Information Security Management System (ISMS) that identifies and treats risks through continuous evaluation \\cite{iso27001_2022}. These frameworks necessitate the adoption of technological solutions capable of mapping raw system data to high-level compliance objectives. The integration of Security Information and Event Management (SIEM) systems provides the data foundation for this automated GRC architecture. SIEM engines ingest raw telemetry from across the enterprise, translating low-level system events into verifiable compliance states. By establishing deterministic baselines, organizations move from reactive, audit-driven reporting to proactive, data-driven security management. This thesis evaluates the implementation of an intelligent system that bridges the gap between technical SIEM telemetry and regulatory control satisfaction.":
    "The cybersecurity industry addresses these vulnerabilities by transitioning toward Continuous Controls Monitoring (CCM). This transition replaces manual sampling with automated validation of security controls. CCM platforms integrate with the technical environment to evaluate configurations, access logs, and system integrity continuously. This automation ensures compliance reflects the current state of the environment rather than a historical record. Modern regulatory mandates codify the requirement for continuous visibility. NIST Special Publication 800-53 Revision 5 requires the transition from static control assessments to ongoing monitoring to validate system integrity \\cite{nist80053_2020}. Similarly, the ISO/IEC 27001:2022 standard requires organizations to establish an Information Security Management System (ISMS) that identifies and treats risks through continuous evaluation \\cite{iso27001_2022}. These frameworks require technological solutions capable of mapping raw system data to governance objectives. Security Information and Event Management (SIEM) systems provide the data foundation for this automated architecture. SIEM engines ingest raw telemetry from across the enterprise, translating system events into verifiable compliance states. By establishing deterministic baselines, organizations move from reactive reporting to data-driven security management. This thesis evaluates the implementation of a system that bridges the gap between technical SIEM telemetry and regulatory control satisfaction.",
    
    "Translating massive volumes of low-level endpoint telemetry into high-level regulatory frameworks presents a significant operational hurdle. SIEM platforms generate thousands of technical alerts, such as SSH authentication failures or unauthorized file modifications, which require immediate correlation against ISO 27001 or SOC 2 control matrices. Manual correlation processes introduce dangerous delays between event detection and compliance validation, creating a window of risk where system vulnerabilities remain unaddressed. Concurrent telemetry sources often produce contradictory states, requiring deterministic resolution mechanisms that existing manual workflows cannot provide.":
    "Translating large volumes of endpoint telemetry into regulatory frameworks presents an operational limitation. SIEM platforms generate technical alerts, such as SSH authentication failures or unauthorized file modifications, which require correlation against ISO 27001 or SOC 2 control matrices. Manual correlation processes introduce delays between event detection and compliance validation, creating risk windows where system vulnerabilities remain unaddressed. Concurrent telemetry sources produce contradictory states, requiring deterministic resolution mechanisms that manual workflows cannot provide.",

    "Calculating real-time compliance metrics across distributed fleets exposes severe data aggregation failures in traditional GRC platforms. Standard relational database implementations often suffer from the N+1 query problem, where the application executes sequential retrieval loops for every individual security control. This architectural flaw imposes a linear $O(N)$ algorithmic complexity on data retrieval, causing geometric performance decay as the number of monitored agents increases \\cite{planetscale_n1}. The resulting latency prevents organizations from achieving a truly continuous monitoring state, as dashboard rendering times exceed the threshold for effective operational visibility. The algorithmic failures of legacy GRC systems stem primarily from their inability to process massive datasets within acceptable temporal bounds. When an organization attempts to map thousands of raw telemetry events to multiple regulatory frameworks, traditional application-level iteration induces severe memory bandwidth exhaustion. By fetching full relational objects through unoptimized query loops, these systems saturate the available computational resources, leading to cascading timeouts and data inconsistency. This performance decay effectively prevents the transition from point-in-time auditing to true continuous monitoring, as the system latency outpaces the rate of telemetry ingestion.":
    "Calculating compliance metrics across distributed fleets exposes data aggregation limitations in traditional GRC platforms. Standard relational database implementations suffer from the N+1 query problem, where the application executes sequential retrieval loops for individual security controls. This architectural flaw imposes a linear $O(N)$ algorithmic complexity on data retrieval, causing geometric performance decay as monitored agents increase \\cite{planetscale_n1}. The resulting latency prevents organizations from achieving continuous monitoring, because dashboard rendering times exceed thresholds for operational visibility. The algorithmic limitations of legacy GRC systems stem from their inability to process large datasets within acceptable temporal bounds. When an organization attempts to map raw telemetry events to multiple regulatory frameworks, application-level iteration induces memory bandwidth exhaustion. By fetching full relational objects through unoptimized query loops, these systems saturate computational resources, leading to timeouts and data inconsistency. This performance decay prevents the transition from point-in-time auditing to continuous monitoring, because system latency outpaces telemetry ingestion.",

    "Legacy GRC interfaces fail to account for the cognitive limitations of security analysts. Rigid, HTML table-heavy dashboards and unoptimized color schemes maximize extraneous cognitive load, leading to rapid desensitization known as alert fatigue. Chronic overstimulation from noisy, unfiltered telemetry streams depletes essential neurotransmitters, causing operators to ignore or misclassify high-severity threats \\cite{mit_alert_fatigue}. This Human-Computer Interaction (HCI) shortcoming transforms security tools into sources of distraction, ultimately degrading incident response times and increasing organizational risk. The cognitive failure inherent in rigid HTML table layouts exacerbates the operational burden on security analysts. Legacy interfaces present high-density, monochromatic data grids that lack semantic visual hierarchy, forcing the human brain to manually filter irrelevant noise from critical signals. This structural rigidity induces rapid desensitization and alert fatigue, where the analyst's sensory threshold increases until critical exploits are routinely overlooked. The absence of adaptive layout modules and the reliance on static data presentation transform these tools into significant sources of organizational risk during high-velocity security incidents.":
    "Legacy GRC interfaces increase cognitive load on security analysts. Rigid HTML table-heavy dashboards and unoptimized color schemes lead to rapid desensitization, known as alert fatigue. Chronic overstimulation from unfiltered telemetry streams causes operators to ignore or misclassify high-severity threats \\cite{mit_alert_fatigue}. This Human-Computer Interaction (HCI) shortcoming degrades incident response times and increases organizational risk. High-density monochromatic data grids lack semantic visual hierarchy, forcing operators to filter noise from critical signals manually. This structural rigidity induces alert fatigue, where the analyst's sensory threshold increases until critical exploits are overlooked. The absence of adaptive layout modules transforms these tools into sources of risk during security incidents.",

    "The development of the Intelligent Compliance Management System (ICMS) focuses on four primary engineering objectives designed to resolve the identified technical and operational gaps:":
    "The development of the ICMS platform addresses the identified technical and operational gaps through four engineering objectives:",

    "    \\item \\textbf{Telemetry Automation:} Automate the ingestion and mapping of Wazuh SIEM telemetry to ISO 27001 and SOC 2 controls, utilizing a deterministic Worst-Case Priority state-mutation algorithm to resolve conflicting evaluations. This objective involves bridging the semantic gap between raw technical states and high-level regulatory controls. By polling the Wazuh Manager's Security Configuration Assessment (SCA) module, the platform retrieves individual check results and correlates them against a pre-seeded compliance matrix. This methodology guarantees that the compliance dashboard always reflects the most conservative security posture, eliminating the risk of false-positive compliance reports.":
    "    \\item \\textbf{Telemetry Automation:} Automate the ingestion and mapping of Wazuh SIEM telemetry to ISO 27001 and SOC 2 controls, utilizing a deterministic Worst-Case Priority state-mutation algorithm to resolve conflicting evaluations. By polling the Wazuh Manager's Security Configuration Assessment (SCA) module, the platform retrieves check results and correlates them against a pre-seeded compliance matrix. This methodology guarantees the compliance dashboard reflects the most conservative security posture, minimizing false-positive compliance reports.",

    "    \\item \\textbf{Performance Optimization:} Eliminate the N+1 database querying bottleneck by engineering $O(1)$ set-based aggregations through the Django ORM, specifically utilizing query annotation and conditional SQL filtering to ensure dashboard latency remains below 200 milliseconds. Rather than executing sequential retrieval loops for every GRC control, the platform leverages the database engine to project complex SQL constraints and conditional aggregations directly onto the relational layer. By computing fleet-wide compliance scores and failure counts internally, the system minimizes data transfer overhead and memory pressure on the application server.":
    "    \\item \\textbf{Performance Optimization:} Eliminate the N+1 database querying bottleneck by engineering $O(1)$ set-based aggregations through the Django ORM. The platform utilizes query annotation and conditional SQL filtering to constrain dashboard latency below 200 milliseconds. The system projects complex SQL constraints and conditional aggregations directly onto the relational layer instead of executing sequential retrieval loops. By computing fleet-wide compliance scores internally, the system reduces data transfer overhead and memory pressure on the application server.",

    "    \\item \\textbf{Security Infrastructure:} Enforce strict infrastructure and session security through a Dockerized virtual bridge network that isolates the PostgreSQL data tier, combined with custom Django REST Framework Role-Based Access Control and stateless JWT rotation. The platform isolates the database within a private virtual network, ensuring that the persistence tier remains unreachable from the public internet. This physical isolation is coupled with an advanced Identity and Access Management (IAM) layer that utilizes stateless JSON Web Token (JWT) rotation and custom permission classes to establish a multi-layered defensive boundary.":
    "    \\item \\textbf{Security Infrastructure:} Enforce strict infrastructure and session security through a Dockerized virtual bridge network that isolates the PostgreSQL data tier, combined with custom Django REST Framework Role-Based Access Control and stateless JWT rotation. The platform isolates the database within a private virtual network, ensuring the persistence tier remains unreachable from external networks. This physical isolation pairs with an Identity and Access Management (IAM) layer that utilizes stateless JSON Web Token (JWT) rotation and custom permission classes.",

    "    \\item \\textbf{UI/UX Engineering:} Mitigate analyst alert fatigue by architecting a modern frontend that replaces rigid HTML tables with flexible layouts and utilizes semantic soft-scaling to improve data parsing speeds. By deprecating structural tables in favor of responsive layout modules, the interface allows data rows to wrap and scale dynamically based on viewport size. The platform utilizes elevation through subtle depth illusions and semantic color scaling to distinguish interactive security cards from static background telemetry, transforming raw data into a structured decision-support matrix.":
    "    \\item \\textbf{UI/UX Engineering:} Mitigate analyst alert fatigue by architecting a modern frontend that replaces rigid HTML tables with flexible layouts. The interface allows data rows to wrap and scale dynamically based on viewport size. The platform uses elevation through depth illusions and semantic color scaling to distinguish interactive security cards from static background telemetry, structuring raw data for decision support.",

    "The research and development of the Intelligent Compliance Management System (ICMS) adopted an Agile software development lifecycle to facilitate iterative progression and dynamic requirement adaptation. This engineering approach commenced with an exhaustive literature review and deep structural analysis of both the ISO/IEC 27001:2022 and SOC 2 Type II regulatory frameworks. By deconstructing abstract governance mandates into deterministic technical variables, the development team engineered a structured schema capable of mapping raw operational telemetry to overarching compliance objectives. Following the establishment of this theoretical baseline, the methodology emphasized the rapid prototyping of API integration layers. The team systematically evaluated the Wazuh Security Configuration Assessment (SCA) module's capabilities, designing specialized client connectors to poll and serialize distributed endpoint states continuously without overwhelming the central SIEM infrastructure.":
    "The research and development of the ICMS platform adopted an Agile software development lifecycle to facilitate iterative progression and requirement adaptation. This engineering approach commenced with a literature review and structural analysis of the ISO/IEC 27001:2022 and SOC 2 Type II regulatory frameworks. By deconstructing abstract governance mandates into deterministic technical variables, the development team engineered a structured schema capable of mapping operational telemetry to compliance objectives. Following the establishment of this baseline, the methodology emphasized the rapid prototyping of API integration layers. The team evaluated the Wazuh Security Configuration Assessment (SCA) module's capabilities and designed specialized client connectors to poll and serialize distributed endpoint states without overloading the central SIEM infrastructure.",

    "Subsequent development sprints focused on the rigorous architectural design and implementation of the backend orchestration system. The methodology prioritized performance optimizations by benchmarking various database aggregation strategies against massive synthetic telemetry datasets, ultimately resulting in the adoption of $O(1)$ set-based query projections to eliminate relational bottlenecks. In the final evaluation phases, the entire platform transitioned into a containerized deployment model utilizing Docker virtual bridge networks. This isolated environment allowed the team to perform rigorous security validation, performance profiling, and stress testing against simulated threat vectors and compliance drift scenarios. By testing the finalized platform within a zero-trust execution sandbox, the methodology ensured that the ICMS delivered verifiable security resilience prior to any proposed enterprise integration.":
    "Subsequent development sprints focused on the architectural design and implementation of the backend orchestration system. The methodology prioritized performance optimization by benchmarking database aggregation strategies against synthetic telemetry datasets, resulting in the adoption of $O(1)$ set-based query projections to eliminate relational bottlenecks. In the evaluation phases, the platform transitioned into a containerized deployment model utilizing Docker virtual bridge networks. This isolated environment allowed the team to perform security validation, performance profiling, and stress testing against simulated threat vectors and compliance drift scenarios. By testing the platform within a zero-trust execution sandbox, the methodology ensured the ICMS delivered verifiable security resilience prior to enterprise integration.",

    "The Intelligent Compliance Management System (ICMS) strictly operates within the boundaries of the ISO/IEC 27001:2022 and SOC 2 Type II compliance frameworks. The platform scope encompasses the ingestion and mapping of endpoint security telemetry specifically from the Wazuh Manager's Security Configuration Assessment (SCA) module. By utilizing the Wazuh REST API, the system retrieves individual check results from active agents and correlates them to the identified governance controls. This data-driven mapping ensures that the compliance state represents an actual reflection of the technical environment's configuration. The polling mechanics utilize the Wazuh REST API to facilitate deterministic data synchronization between the SIEM and the GRC layers. The system initiates authenticated requests to the SCA module, retrieving detailed payloads that describe the pass or fail status of specific configuration checks on monitored agents. Each retrieved check ID is cross-referenced against the ICMS seed matrix, which acts as a mapping key between low-level technical identifiers and high-level governance controls. This correlation allows the platform to translate technical events into verifiable regulatory violations automatically.":
    "The ICMS platform operates within the boundaries of the ISO/IEC 27001:2022 and SOC 2 Type II compliance frameworks. The scope encompasses the ingestion and mapping of endpoint security telemetry from the Wazuh Manager's Security Configuration Assessment (SCA) module. By utilizing the Wazuh REST API, the system retrieves check results from active agents and correlates them to identified governance controls. This data mapping ensures the compliance state represents the technical environment's configuration. The system initiates authenticated requests to the SCA module to retrieve payloads describing the pass or fail status of configuration checks on monitored agents. Each retrieved check ID is cross-referenced against the ICMS seed matrix, which acts as a mapping key between technical identifiers and governance controls. This correlation translates technical events into regulatory violations.",

    "The implementation boundary is restricted to a containerized Docker ecosystem designed for secure, isolated operation. This environment utilizes a private virtual bridge network to facilitate communication between the PostgreSQL database, Redis message broker, Celery workers, and the Django-React application stack. This architectural scope ensures that the data persistence tier remains inaccessible to external networks, maintaining a secure baseline for the storage of sensitive compliance telemetry and organizational policies. To maintain the focus on Governance, Risk, and Compliance (GRC) monitoring, several operational domains remain outside the project scope. The system does not perform active Incident Response (IR) actions, such as isolating compromised endpoints or terminating malicious processes. The platform does not conduct network packet sniffing or automated remediation of configuration drift. While the system evaluates and reports on the compliance state, it does not mutate endpoint configurations; all infrastructure remediation remains the responsibility of dedicated IT operations teams.":
    "The implementation boundary restricts the system to a containerized Docker ecosystem for isolated operation. This environment utilizes a private virtual bridge network to facilitate communication between the PostgreSQL database, Redis message broker, Celery workers, and the Django-React application stack. This architectural scope ensures the data persistence tier remains inaccessible to external networks, maintaining a baseline for storing compliance telemetry and organizational policies. Several operational domains remain outside the project scope to maintain focus on Governance, Risk, and Compliance (GRC) monitoring. The system does not perform active Incident Response (IR) actions, such as isolating compromised endpoints or terminating malicious processes. The platform does not conduct network packet sniffing or automated remediation of configuration drift. The system evaluates and reports on the compliance state but does not mutate endpoint configurations; infrastructure remediation remains the responsibility of dedicated IT operations teams.",

    "The implementation of the Intelligent Compliance Management System presents a highly viable engineering initiative, supported by extensive technical, economic, and operational feasibility validations. Technically, the platform leverages the mature, open-source Wazuh SIEM ecosystem alongside the proven Django and React frameworks, ensuring that all architectural dependencies are reliable, actively maintained, and fully capable of handling high-velocity telemetry streams. The decision to containerize the entire application stack using Docker ensures absolute deployment feasibility across heterogeneous hardware environments. By decoupling the application logic from the host operating system, the system guarantees deterministic execution and simplified scaling, allowing organizations to deploy the solution on existing internal infrastructure without requiring specialized hardware procurement. Economically, the ICMS platform introduces massive cost-reduction paradigms compared to proprietary Software-as-a-Service (SaaS) compliance solutions. By utilizing an entirely open-source technology stack, the system eliminates exorbitant recurring licensing fees and vendor lock-in risks associated with commercial GRC vendors. Organizations can achieve comprehensive continuous controls monitoring utilizing their existing open-source SIEM infrastructure, shifting the financial model from high operational expenditure (OpEx) to a minimal, sustainable maintenance profile.":
    "The implementation of the ICMS platform is technically and economically feasible. Technically, the platform leverages the open-source Wazuh SIEM ecosystem alongside the Django and React frameworks, ensuring architectural dependencies can handle telemetry streams. Containerizing the application stack using Docker ensures deployment across heterogeneous hardware environments. By decoupling the application logic from the host operating system, the system guarantees deterministic execution and allows organizations to deploy the solution on existing infrastructure without specialized hardware procurement. Economically, the platform reduces costs compared to proprietary Software-as-a-Service (SaaS) compliance solutions. By utilizing an open-source technology stack, the system eliminates recurring licensing fees and vendor lock-in risks associated with commercial GRC vendors. Organizations can achieve continuous controls monitoring utilizing existing open-source SIEM infrastructure, shifting the financial model from high operational expenditure (OpEx) to a maintenance profile.",

    "Operationally, the intuitive interface and automated telemetry mapping drastically reduce the manual labor hours traditionally required for evidence collection, proving the system is not only feasible but actively enhances the operational efficiency of enterprise Security Operations Centers (SOC).":
    "Operationally, the interface and automated telemetry mapping reduce the manual labor hours required for evidence collection, increasing the operational efficiency of Security Operations Centers (SOC).",

    "The Intelligent Compliance Management System provides necessary continuous monitoring capabilities specifically tailored for industries constrained by rigorous data privacy and governance mandates. In the Financial Technology (FinTech) sector, where rapid transaction processing and dynamic infrastructure scaling outpace traditional point-in-time auditing, ICMS delivers the real-time assurance required to satisfy regulatory bodies. FinTech startups processing payment data can utilize the platform to maintain continuous, verifiable adherence to SOC 2 Type II and internal security policies, mitigating the risk of devastating financial penalties or loss of operational licenses due to undetected configuration drift in their ephemeral cloud environments.":
    "The ICMS platform provides continuous monitoring capabilities for industries constrained by data privacy and governance mandates. In the Financial Technology (FinTech) sector, where transaction processing and infrastructure scaling outpace point-in-time auditing, the platform delivers the assurance required to satisfy regulatory bodies. FinTech startups processing payment data can utilize the platform to maintain adherence to SOC 2 Type II and internal security policies, mitigating the risk of financial penalties or loss of operational licenses due to undetected configuration drift in cloud environments.",

    "Similarly, the platform delivers immense strategic value to the Healthcare sector and emerging cloud-native startups managing highly sensitive Protected Health Information (PHI). Healthcare organizations must constantly validate their infrastructure against stringent frameworks like HIPAA and ISO 27001 to prevent catastrophic data breaches. ICMS automates the translation of technical vulnerabilities into high-level compliance violations, allowing hospital networks to maintain a secure, deterministic posture across thousands of distributed endpoints. By providing absolute data sovereignty within an isolated Docker environment, the platform ensures that sensitive operational telemetry never leaves the organization's private network, making it the ideal solution for entities operating under the strictest global confidentiality requirements.":
    "The platform also applies to the Healthcare sector for organizations managing Protected Health Information (PHI). Healthcare organizations validate their infrastructure against frameworks like HIPAA and ISO 27001 to prevent data breaches. The platform automates the translation of technical vulnerabilities into compliance violations, allowing hospital networks to maintain a deterministic posture across distributed endpoints. By providing data sovereignty within an isolated Docker environment, the platform ensures operational telemetry remains within the organization's private network, supporting entities operating under confidentiality requirements.",

    "This thesis consists of seven chapters that detail the research, design, and implementation of the Intelligent Compliance Management System (ICMS). Chapter 2 evaluates existing literature regarding Governance, Risk, and Compliance (GRC) frameworks and Security Information and Event Management (SIEM) integration. Chapter 3 defines the functional and non-functional requirements of the platform while establishing the high-level system architecture. Chapter 4 provides the detailed system design, incorporating Unified Modeling Language (UML) diagrams to represent the logical and physical data flows. Chapter 5 focuses on the implementation phase, detailing the backend algorithms and containerized orchestration used to achieve continuous monitoring. Chapter 6 outlines the system testing protocols and evaluates the platform's performance against defined accuracy and latency metrics. Chapter 7 concludes the research by summarizing the project's contributions and proposing directions for future work.":
    "This thesis consists of seven chapters detailing the research, design, and implementation of the ICMS platform. Chapter 2 evaluates literature regarding Governance, Risk, and Compliance (GRC) frameworks and Security Information and Event Management (SIEM) integration. Chapter 3 defines the functional and non-functional requirements and establishes the system architecture. Chapter 4 provides the system design, incorporating Unified Modeling Language (UML) diagrams to represent logical and physical data flows. Chapter 5 focuses on implementation, detailing backend algorithms and containerized orchestration. Chapter 6 outlines testing protocols and evaluates performance against accuracy and latency metrics. Chapter 7 summarizes the project's contributions and proposes directions for future work."
}

for old, new in replacements.items():
    if old not in text:
        print(f"NOT FOUND: {old[:50]}...")
    text = text.replace(old, new)

with open('chapter1.tex', 'w', encoding='utf-8') as f:
    f.write(text)

print("Chapter 1 rewritten.")
