with open('chapter3.tex', 'r', encoding='utf-8') as f:
    text = f.read()

replacements = {
    "Legacy compliance management systems rely heavily on manual spreadsheet auditing and fragmented Software-as-a-Service (SaaS) platforms. In these traditional environments, governance teams attempt to map complex regulatory standards, such as ISO/IEC 27001:2022, to specific technical controls using decentralized, static documents. This approach introduces significant human error, lacks version control, and fails to maintain referential integrity across overlapping frameworks. The manual tracking of thousands of discrete configuration states results in heavy operational labor expenditures and an unsustainable administrative burden.":
    "Legacy compliance management systems rely on manual spreadsheet auditing and fragmented Software-as-a-Service (SaaS) platforms. Governance teams attempt to map regulatory standards, such as ISO/IEC 27001:2022, to technical controls using decentralized, static documents. This approach introduces human error, lacks version control, and fails to maintain referential integrity across overlapping frameworks. The manual tracking of configuration states results in heavy operational labor expenditures and administrative burden.",

    "Furthermore, existing point-in-time auditing solutions perform delayed security assessments, meaning the data collected from the internal network systems becomes stale immediately upon generation. These legacy platforms often employ generic software flows lacking specialized relational constraints, leading to severe latency when processing high-volume endpoint telemetry and an inability to maintain determinism in vulnerability resolution. The reliance on black-box proprietary SaaS architectures also introduces severe data sovereignty risks, as internal compliance metrics and potentially sensitive infrastructure configurations are transmitted to multi-tenant public cloud environments.":
    "Existing point-in-time auditing solutions perform delayed security assessments, meaning data collected from internal network systems becomes stale upon generation. Legacy platforms employ generic software flows lacking specialized relational constraints, leading to latency when processing endpoint telemetry and an inability to maintain determinism in vulnerability resolution. The reliance on proprietary SaaS architectures introduces data sovereignty risks, because internal compliance metrics and infrastructure configurations are transmitted to multi-tenant public cloud environments.",

    "To overcome the critical limitations of legacy spreadsheet mapping and asynchronous SIEM aggregation, the Intelligent Compliance Management System (ICMS) introduces a centralized, deterministic orchestration engine. The proposed system leverages a multi-tier architectural topology designed to maintain strict separation of concerns while providing real-time compliance tracking within a single-tenant, isolated environment.":
    "To overcome the limitations of legacy spreadsheet mapping and asynchronous SIEM aggregation, the ICMS platform introduces a centralized, deterministic orchestration engine. The system leverages a multi-tier architectural topology designed to maintain separation of concerns while providing compliance tracking within a single-tenant, isolated environment.",

    "Selecting the Python-based Django framework for the backend application layer provides a high-productivity environment characterized by an integrated Object-Relational Mapper (ORM) and native security middleware. The Django ORM facilitates the implementation of the platform's performance optimizations, specifically the $O(1)$ set-based database aggregations that outpace legacy sequential retrieval patterns. By utilizing complex query projections and conditional filtering at the ORM level, the system ensures that high-volume telemetry remains computationally manageable. Furthermore, the Django REST Framework (DRF) extends these capabilities by providing modular serialization pipelines and built-in support for sophisticated authentication schemas, including stateless JSON Web Token (JWT) rotation.":
    "Selecting the Python-based Django framework for the backend application layer provides an environment characterized by an integrated Object-Relational Mapper (ORM) and native security middleware. The Django ORM facilitates the implementation of performance optimizations, specifically $O(1)$ set-based database aggregations. By utilizing query projections and conditional filtering at the ORM level, the system ensures high-volume telemetry remains computationally manageable. The Django REST Framework (DRF) extends these capabilities by providing modular serialization pipelines and support for authentication schemas, including stateless JSON Web Token (JWT) rotation.",

    "The selection of React 18 and the Vite build tool establishes a high-performance Single Page Application (SPA) architecture designed for complex data visualization. React's Virtual DOM provides a significant theoretical advantage in the context of security monitoring, as it allows the interface to render high-frequency compliance state changes without causing browser thread execution delays. This reactive rendering paradigm ensures that analysts maintain a fluid experience even when viewing dense matrices of real-time SIEM alerts. Vite further enhances the development and production lifecycle by utilizing native ES modules and Hot Module Replacement (HMR), drastically reducing build latency compared to legacy Webpack-based bundling strategies.":
    "The selection of React 18 and the Vite build tool establishes a Single Page Application (SPA) architecture designed for data visualization. React's Virtual DOM provides an advantage in the context of security monitoring, allowing the interface to render compliance state changes without causing browser thread execution delays. This reactive rendering ensures analysts maintain an operational experience when viewing dense matrices of SIEM alerts. Vite enhances the development and production lifecycle by utilizing native ES modules and Hot Module Replacement (HMR), reducing build latency compared to legacy Webpack-based bundling strategies.",

    "PostgreSQL serves as the primary data persistence tier, providing the strict ACID compliance required for maintaining the integrity of organizational compliance records. The relational engine is uniquely suited for handling the high concurrent read/write loads generated by continuous SIEM telemetry ingestion and automated framework mapping. By utilizing B-Tree indexing and advanced relational constraints, PostgreSQL guarantees that cross-framework compliance metrics remain accurate and accessible. This data integrity is essential for satisfying the rigorous evidence requirements of ISO 27001 and SOC 2 audits, where the historical state of security controls must remain verifiable and immutable.":
    "PostgreSQL serves as the primary data persistence tier, providing the ACID compliance required for maintaining the integrity of organizational compliance records. The relational engine handles the concurrent read/write loads generated by SIEM telemetry ingestion and automated framework mapping. By utilizing B-Tree indexing and relational constraints, PostgreSQL guarantees cross-framework compliance metrics remain accurate. This data integrity satisfies the evidence requirements of ISO 27001 and SOC 2 audits, where the historical state of security controls must remain verifiable and immutable.",

    "To ensure the platform remains responsive during data-heavy operations, the architecture incorporates Celery and Redis as the asynchronous orchestration layer. Decoupling I/O-bound tasks, such as the periodic synchronization of telemetry from the Wazuh SIEM REST API, from the main Django application thread prevents HTTP request timeouts and maintains dashboard availability. Redis acts as a high-performance message broker, facilitating the reliable transport of task payloads between the web server and the background worker fleet. This distributed task execution model allows the platform to scale its ingestion capacity without impeding the real-time interaction capabilities of the primary API service.":
    "To ensure the platform remains responsive during data-heavy operations, the architecture incorporates Celery and Redis as the asynchronous orchestration layer. Decoupling I/O-bound tasks, such as the periodic synchronization of telemetry from the Wazuh SIEM REST API, from the main Django application thread prevents HTTP request timeouts and maintains dashboard availability. Redis acts as a message broker, facilitating the transport of task payloads between the web server and the background worker fleet. This distributed task execution model allows the platform to scale its ingestion capacity without impeding the interaction capabilities of the primary API service.",

    "The Presentation Tier consists of a React-based SPA that manages the user session and provides a high-fidelity interface for compliance monitoring. This tier communicates with the Application Logic Tier via stateless JSON payloads over an encrypted HTTPS channel. By offloading the state management and rendering logic to the client-side browser environment, the system ensures that the central server resources remain available for complex data processing and framework mapping tasks.":
    "The Presentation Tier consists of a React-based SPA that manages the user session and provides an interface for compliance monitoring. This tier communicates with the Application Logic Tier via stateless JSON payloads over an encrypted HTTPS channel. By offloading the state management and rendering logic to the client-side browser environment, the system ensures central server resources remain available for data processing and framework mapping tasks.",

    "The Application Logic Tier, powered by the Django REST Framework, serves as the central gateway for all compliance orchestration. This tier manages the Identity and Access Management (IAM) lifecycle, including the generation and rotation of JSON Web Tokens (JWT). All interactions with the Data Persistence Tier occur via binary TCP connections managed by the Django ORM, which enforces relational integrity and executes the platform's query aggregations. Asynchronous task execution relies on a distributed architecture incorporating Celery and a Redis-based message broker. The system utilizes a Pub/Sub messaging model to enqueue compliance synchronization tasks, allowing Celery workers to process telemetry data from the external Wazuh SIEM Manager out-of-band. The complete protocol flow and multi-tier layout of this system are mapped in Figure \\ref{fig:detailed_architecture}.":
    "The Application Logic Tier, powered by the Django REST Framework, serves as the gateway for compliance orchestration. This tier manages the Identity and Access Management (IAM) lifecycle, including the generation and rotation of JSON Web Tokens (JWT). Interactions with the Data Persistence Tier occur via TCP connections managed by the Django ORM, which enforces relational integrity and executes query aggregations. Asynchronous task execution relies on a distributed architecture incorporating Celery and a Redis-based message broker. The system utilizes a Pub/Sub messaging model to enqueue compliance synchronization tasks, allowing Celery workers to process telemetry data from the external Wazuh SIEM Manager out-of-band. Figure \\ref{fig:detailed_architecture} maps the protocol flow and multi-tier layout.",

    "The implementation of a Dockerized virtual bridge network establishes a Zero Trust perimeter that physically isolates the data persistence tier from external network environments. By restricting the PostgreSQL and Redis services to an internal, non-routable network, the architecture ensures that these sensitive components remain invisible to unauthorized host-level scans. Managing data persistence across container lifecycles requires the utilization of Docker volumes to prevent the loss of critical compliance telemetry. Orchestrating the system startup sequence through deterministic health-check dependencies ensures that the ICMS platform remains resilient against race conditions during deployment. The configuration defines explicit execution priorities, where the Django API container monitors the execution of system-level commands, such as the PostgreSQL readiness utility, before initiating database migrations or starting the WSGI server. This multi-tier isolation and health monitoring network is depicted in Figure \\ref{fig:docker_mesh}.":
    "The implementation of a Dockerized virtual bridge network establishes a perimeter that isolates the data persistence tier from external network environments. By restricting the PostgreSQL and Redis services to an internal, non-routable network, the architecture ensures these components remain inaccessible to host-level scans. Managing data persistence across container lifecycles requires Docker volumes to prevent the loss of compliance telemetry. Orchestrating the system startup sequence through deterministic health-check dependencies ensures the platform remains resilient against race conditions during deployment. The configuration defines execution priorities, where the Django API container monitors the execution of system-level commands before initiating database migrations or starting the WSGI server. Figure \\ref{fig:docker_mesh} depicts this multi-tier isolation and health monitoring network.",

    "Requirement engineering for the Intelligent Compliance Management System (ICMS) involves a rigorous mapping of regulatory mandates to technical specifications. Aligning the platform with ISO/IEC 27001:2022 and SOC 2 Type II standards requires the translation of abstract governance objectives into deterministic functional capabilities. This process ensures that every architectural component satisfies a specific compliance or operational constraint, eliminating the risk of unmapped vulnerabilities. By prioritizing automated telemetry ingestion and high-performance data aggregation, the requirement analysis phase establishes the foundation for a system capable of maintaining real-time visibility across distributed infrastructure.":
    "Requirement engineering for the ICMS platform involves mapping regulatory mandates to technical specifications. Aligning the platform with ISO/IEC 27001:2022 and SOC 2 Type II standards requires the translation of governance objectives into deterministic functional capabilities. This process ensures architectural components satisfy compliance or operational constraints. The requirement analysis phase establishes the foundation for a system capable of maintaining visibility across distributed infrastructure by prioritizing automated telemetry ingestion and data aggregation.",

    "The functional requirements define the explicit capabilities the ICMS architecture must possess to execute its core operations:":
    "The functional requirements define the capabilities the ICMS architecture must possess to execute its core operations:",

    "The operational efficacy of the ICMS platform relies heavily on delivering a high-fidelity user experience tailored to its primary actors: the System Administrator and the Security Auditor. The System Administrator requires a friction-free control plane capable of managing deep infrastructure settings without exposing complex database commands. They must possess the capability to configure the synchronization lifecycle, manage RBAC privileges across user accounts, and override automated telemetry when necessary. Consequently, the interface must present these administrative controls with a low cognitive load, utilizing immediate visual feedback through the Cyber-SaaS component library to confirm successful CRUD operations within the Django ORM.":
    "The operational efficacy of the ICMS platform relies on delivering a user experience tailored to its primary actors: the System Administrator and the Security Auditor. The System Administrator requires a control plane capable of managing infrastructure settings without exposing database commands. They must possess the capability to configure the synchronization lifecycle, manage RBAC privileges across user accounts, and override automated telemetry when necessary. The interface must present these administrative controls with a low cognitive load, utilizing visual feedback through the component library to confirm successful CRUD operations within the Django ORM.",

    "Conversely, the Security Auditor interacts with the platform strictly as an analytical tool to assess regulatory adherence. Their primary requirement is the rapid parsing of high-volume compliance data without the visual clutter associated with legacy GRC software. The auditor demands a strict RBAC boundary that prevents accidental modification of critical infrastructure mapping while offering uninterrupted access to historical scan logs and PDF export functionalities. The React SPA architecture must guarantee that even during heavy concurrent data ingestion from the Wazuh SIEM, the dashboard remains completely responsive, employing deep memoization to ensure that continuous DOM updates do not introduce browser thread execution delays.":
    "The Security Auditor interacts with the platform as an analytical tool to assess regulatory adherence. Their primary requirement is parsing compliance data without the visual clutter associated with legacy GRC software. The auditor requires an RBAC boundary that prevents modification of infrastructure mapping while offering access to historical scan logs and PDF export functionalities. The React SPA architecture must guarantee the dashboard remains responsive during concurrent data ingestion from the Wazuh SIEM, employing memoization to ensure DOM updates do not introduce browser thread execution delays.",

    "This section outlines the systemic data exchange boundaries and flow orchestrations utilized by the ICMS to securely synchronize external SIEM telemetry with the internal compliance tracking engine.":
    "This section outlines the systemic data exchange boundaries and flow orchestrations utilized by the platform to synchronize external SIEM telemetry with the internal compliance tracking engine.",

    "The Context Diagram defines the highest level of interaction between the ICMS core logic and external entities, illustrating the fundamental boundaries of the application and the macroscopic data streams required for operation. Figure \\ref{fig:context_diagram} maps the interaction flow from human operators to automated infrastructure components.":
    "The Context Diagram defines the interaction between the ICMS core logic and external entities, illustrating the boundaries of the application and the data streams required for operation. Figure \\ref{fig:context_diagram} maps the interaction flow from human operators to infrastructure components.",

    "The Level-1 Data Flow Diagram (DFD) offers a granular visualization of how data payloads traverse the platform's internal architecture, specifically mapping the transformation of raw SIEM logs into structured compliance metrics. Figure \\ref{fig:dfd_level_1} outlines the deterministic pipeline executed by the ICMS.":
    "The Level-1 Data Flow Diagram (DFD) offers a visualization of how data payloads traverse the platform's internal architecture, mapping the transformation of raw SIEM logs into structured compliance metrics. Figure \\ref{fig:dfd_level_1} outlines the deterministic pipeline executed by the ICMS.",

    "The use cases define the exhaustive interaction sequences available to authenticated actors, providing deterministic state definitions for every critical platform operation.":
    "The use cases define the interaction sequences available to authenticated actors, providing deterministic state definitions for platform operations.",

    "Figure \\ref{fig:use_case_diagram} maps the primary operational workflows orchestrated by the System Administrator and the Security Auditor, establishing clear boundaries of execution based on the platform's internal RBAC implementation.":
    "Figure \\ref{fig:use_case_diagram} maps the operational workflows orchestrated by the System Administrator and the Security Auditor, establishing boundaries of execution based on the platform's internal RBAC implementation.",

    "The following tabular specifications explicitly define the algorithmic flows, authentication prerequisites, and resulting persistence states for each critical operation.":
    "The following tabular specifications define the algorithmic flows, authentication prerequisites, and resulting persistence states for each operation."
}

for old, new in replacements.items():
    if old not in text:
        print(f"NOT FOUND: {old[:50]}...")
    text = text.replace(old, new)

with open('chapter3.tex', 'w', encoding='utf-8') as f:
    f.write(text)

print("Chapter 3 rewritten.")
